# Generated by Django 4.1.3 on 2022-11-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_role_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/avatar.svg', null=True, upload_to='profiles', verbose_name='фотка'),
        ),
    ]
