# Generated by Django 4.1.3 on 2022-11-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, verbose_name='адрес')),
                ('floor', models.PositiveIntegerField(verbose_name='этаж')),
                ('max_floor', models.PositiveIntegerField(verbose_name='максимум этажей')),
                ('rooms', models.PositiveIntegerField(verbose_name='количество комнат')),
                ('pets', models.BooleanField(default=False, verbose_name='питомцы')),
                ('for_family', models.BooleanField(verbose_name='для семьи')),
                ('long_term', models.BooleanField(verbose_name='долгосрочный съем')),
                ('rating', models.PositiveIntegerField(verbose_name='рейтинг')),
                ('verified', models.BooleanField(verbose_name='верифицировано')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'имущество',
                'verbose_name_plural': 'имущества',
            },
        ),
    ]
