# Generated by Django 4.1.3 on 2022-11-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rating',
        ),
        migrations.AddField(
            model_name='property',
            name='count_number',
            field=models.PositiveIntegerField(default=0, verbose_name='количество голосов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='total_stars',
            field=models.PositiveIntegerField(default=0, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/images/'),
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='properties/videos/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='property.property')),
            ],
        ),
    ]
