# Generated by Django 4.1.3 on 2022-11-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_count_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(choices=[('Алмазарский', 'Almazar'), ('Бектемирский', 'Bektemir'), ('Мирабадский', 'Mirabad'), ('Мирзо-Улугбекский', 'Mirzo'), ('Сергелийский', 'Sergeli'), ('Чиланзарский', 'Chilanzar'), ('Шайхантаурский', 'Shayhantaur'), ('Юнусабадский', 'Yunusabad'), ('Яккасарайский', 'Yakkasaray'), ('Яшнабадский', 'Yashnabad'), ('Учтепинский', 'Uchtepa')], default='Мирзо-Улугбекский', max_length=128),
            preserve_default=False,
        ),
    ]
