# Generated by Django 4.1.3 on 2022-11-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_price_property_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
