# Generated by Django 4.1.3 on 2022-11-06 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0008_property_description_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_month', models.PositiveIntegerField(default=10)),
                ('arrival_year', models.PositiveIntegerField(default=2022)),
                ('departure_month', models.PositiveIntegerField(default=12)),
                ('departure_year', models.PositiveIntegerField(default=2022)),
                ('comment', models.TextField(null=True)),
                ('status', models.CharField(choices=[('В ожидании', 'Pending'), ('Принят', 'Accepted'), ('Отказан', 'Rejected')], default='В ожидании', max_length=32)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
    ]
